name: Deploy to Replicate

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
          sudo chmod +x /usr/local/bin/cog
          cog --version

      - name: Login to Replicate
        run: |
          echo "${{ secrets.REPLICATE_CLI_TOKEN }}" | cog login --token-stdin

      - name: Push to Replicate
        run: |
          cog push r8.im/danksly/decensor
